# Generated by Django 5.1.3 on 2024-12-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netplusapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_limit',
            field=models.CharField(choices=[('All', 'Adulto'), ('Kids', 'Niño')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age_limit',
            field=models.CharField(choices=[('All', 'Adulto'), ('Kids', 'Niño')], max_length=10),
        ),
    ]
